version: '3'
services:
  timemachine:
    network_mode: "host"
    environment:
      - CUSTOM_AFP_CONF=false
      - LOG_LEVEL=info
      - MIMIC_MODEL=TimeCapsule6,106
      - PASSWORD=timemachine
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachine
      - VOLUME_SIZE_LIMIT=0
    restart: unless-stopped
    ports:
     - "548:548"
     - "636:636"
    volumes:
     - /path/to/your/timemachine/volume:/timemachine
     - ./timemachine-netatalk:/var/netatalk
     - ./timemachine-logs:/var/log/supervisor
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: timemachine
    image: mbentley/timemachine:latest
